from django.urls import path
from . import views

urlpatterns = [
    path('Einführung/', views.lesson_1_introduction, name='lesson_1_introduction'),
    path('Blockly_Games/Vorwort/', views.lesson_1_blockly_games_explanation, name='lesson_1_blockly_games_explanation'),
    path('Blockly_Games/Puzzle/', views.lesson_1_blockly_games_puzzle, name='lesson_1_blockly_games_puzzle'),
    path('Blockly_Games/Labyrinth/Spielfeld/', views.lesson_1_labyrinth_preparation,
         name='lesson_1_labyrinth_preparation'),
    path('Anweisungen/', views.lesson_1_instructions, name='lesson_1_instructions'),
    path('Bedingte_Anweisungen/', views.lesson_1_conditional_statements, name='lesson_1_conditional_statements'),
    path('Schleifen/', views.lesson_1_loop, name='lesson_1_loop'),
    path('Blockly_Games/Labyrinth/', views.lesson_1_blockly_games_labyrinth, name='lesson_1_blockly_games_labyrinth'),
    path('Blockly_Games/Vogel/Spielfeld/', views.lesson_1_bird_preparation, name='lesson_1_bird_preparation'),
    path('Variablen/', views.lesson_1_variables, name='lesson_1_variables'),
    path('Bedingte_Anweisungen/Zusatz/', views.lesson_1_conditional_statements_addition,
         name='lesson_1_conditional_statements_addition'),
    path('Logischer_Operator/Und/', views.lesson_1_logic_and, name='lesson_1_logic_and'),
    path('Blockly_Games/Vogel/', views.lesson_1_blockly_games_bird, name='lesson_1_blockly_games_bird'),
    path('Blockly_Games/Schildkröte/Spielfeld/', views.lesson_1_turtle_preparation, name='lesson_1_turtle_preparation'),
    path('Schleifen/Zählschleife/', views.lesson_1_counting_loop, name='lesson_1_counting_loop'),
    path('Variablen/Zusatz/', views.lesson_1_variables_addition, name='lesson_1_variables_addition'),
    path('Schleifen/Zählschleife/', views.lesson_1_counting_loop, name='lesson_1_counting_loop'),
    path('Funktionen/', views.lesson_1_functions, name='lesson_1_functions'),
    path('Blockly_Games/Schildkröte/', views.lesson_1_blockly_games_turtle, name='lesson_1_blockly_games_turtle'),
    path('Blockly_Games/Film/Spielfeld/', views.lesson_1_movie_preparation, name='lesson_1_movie_preparation'),
    path('Blockly_Games/Film/', views.lesson_1_blockly_games_movie, name='lesson_1_blockly_games_movie'),
    path('Blockly_Games/Teich/Spielfeld/', views.lesson_1_pond_preparation, name='lesson_1_pond_preparation'),
    path('Blockly_Games/Teich/', views.lesson_1_blockly_games_pond, name='lesson_1_blockly_games_pond'),
    path('Blockly_Games/Teich/Lösung/', views.lesson_1_pond_solution, name='lesson_1_pond_solution'),
    path('Zusammenfassung/', views.lesson_1_wrap_up, name='lesson_1_wrap_up'),
]
